//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockDosp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int id_login { get; set; }
        public string rut_usuario { get; set; }
        public string clave { get; set; }
    }
}
