//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockDosp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.salida_producto = new HashSet<salida_producto>();
        }
    
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public int cantidad { get; set; }
        public string observacion { get; set; }
        public int tipo_producto { get; set; }
        public int proveedor { get; set; }
    
        public virtual proveedor proveedor1 { get; set; }
        public virtual tipo_producto tipo_producto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salida_producto> salida_producto { get; set; }
    }
}
