//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockDosp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salida_producto
    {
        public int id_salida_producto { get; set; }
        public int producto { get; set; }
        public System.DateTime fecha { get; set; }
        public string observacion { get; set; }
    
        public virtual producto producto1 { get; set; }
    }
}
